#!/usr/bin/env node

const chalk       = require('chalk')
const api         = require('./api')

const group       = require('./modules/group')
const commands    = require('./modules/commands')
const execute     = require('./modules/execute')
const help        = require('./modules/help')
const print       = require('./modules/print')
const list        = require('./modules/list')
const error       = require('./modules/error')

const command = process.argv[2]
const args = process.argv.slice(3)

switch (command) {

  case 'ls':
  case 'list':
    if(args.length !== 0) {
      error('Nope, not using that right!')
      help()
      break
    }
    print(api)
    break

  case 'group':
    list(api, args)
    break

  case 'open':
  case 'run':
    if (args.length === 1) {
      if (api.listExists(args[0])) {
        execute(api, args[0])
        break
      } else {
        error('Group not found.')
        break
      }
    } else {
      error('Nope, not using that right!')
      help()
      break
    }

  case 'help':
  case undefined:
    help()
    break

  default:
    if (api.listExists(command)) {
      group(api, args, command)
    } else {
      error('Group not found. Did you mean to do something else?')
      help('root')
    }
}

api.save()
